# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Initialize submodules
      run: git submodule init && git submodule update
    - name: Build debezium
      run: cd debezium && mvn clean package -pl debezium-core,debezium-connector-postgres && cd ..
    - name: Build debezium container
      run: cd debezium && chmod +x docker-build.sh && ./docker-build.sh && cd ..
    - name: Build with Gradle
      run: ./gradlew build
